import {
    authMode,
    configuredPartitions,
    defaultPartitionId,
    fhirEndpoint,
    gcpClientId,
    gcpScopes,
    msalAuthorityBase,
    msalClientId,
    msalScope,
    msalTenantId,
    postLogoutRedirectUri,
    redirectUri,
    usePartitions,
} from './config/runtime';

export const parameters = {
    authMode,
    fhirEndpoint,
    partitionId: defaultPartitionId,
    partitionsList: configuredPartitions.join('.'),
    usePartitions,
    clientId: msalClientId,
    authority: msalAuthorityBase,
    tenantId: msalTenantId,
    scope: msalScope,
    gcpClientId,
    gcpScopes,
    redirectURI: redirectUri,
    postLogoutRedirectURI: postLogoutRedirectUri,
};
